<?php

namespace AppBundle\Repository;

/**
 * AccountRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AccountRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
