# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    get.attributes:
        class: AppBundle\Services\GetUserAttributes
        arguments: ['%ldapServer%', '%ldapServerPort%', '%ldapSearchUser%', '%ldapSearchPassword%', '%ldapSearchBaseDn%']

    ldap:
        class: 'Symfony\Component\Ldap\LdapClient'
        arguments:
            - %ldapServer%      # host
            - %ldapServerPort%  # port
            - 2                 # version
            - false             # SSL
            - false             # TLS

#
# add some utilities to twig templates
#

#    app.twig_extension:
#        class: AppBundle\Services\AppExtension
#        public: false
#        tags:
#            - { name: twig.extension }
#        arguments: ["@service_container", "@doctrine"]

